version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    target-branch: 'main'
    ignore:
      - dependency-name: '*'
        paths:
          - 'examples/**'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'