packages:
  - 'packages/*'
  - 'examples/*'

catalog:
  "@types/node": "20.19.0"
  "@types/react": "18.2.55"
  "@types/react-dom": "18.2.19"
  "react": "18.2.0"
  "react-dom": "18.2.0"
  "@tanstack/react-query": "5.81.5"
  "dedot": "0.16.0"
  "@dedot/chaintypes": "0.152.0"
  "tsup": "8.5.0"
