packages:
  - 'packages/*'
  - 'examples/*'

catalog:
  "@types/react": "18.2.55"
  "@types/react-dom": "18.2.19"
  "react": "18.2.0"
  "react-dom": "18.2.0"
  "@tanstack/react-query": "5.81.5"
  "dedot": "0.14.1"
  "@dedot/chaintypes": "0.123.0"
  "tsup": "8.5.0"
